apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: ocpob-swf
spec:
  type: RemoteSource
  #envs:
  # envs can be used to set variables during build
  #- name: MY_CUSTOM_ENV
  #  value: "my value"
  gitSource:
    #contextDir: 
    reference: main
    uri: 'https://github.com/rgolangh/ocpob-swf'
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: ocpob-swf
